language: php

sudo: false

php:
- 5.2
- 5.3
- 5.4
- 5.5
- 5.6
- hhvm
- nightly

branches:
  only:
    - master
    - develop
    - /^(?i:release)\/.*$/

env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=4.2.4 WP_MULTISITE=0
- WP_VERSION=4.1.1 WP_MULTISITE=0
- WP_VERSION=3.9.2 WP_MULTISITE=0

matrix:
  allow_failures:
    - php: nightly

before_script:
- sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '5.2' ]; then pecl install timezonedb; fi"
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit

